### ISSUE TITLE
TlsConnector::connect() returning a Result<Future<Item=Result<_,_>> is inconvenient

### ISSUE THREAD

**Issue by sdroege** [async-rs/async-tls#10]
It requires writing

```rust
let conn = connector.connect(...)?.await?;
```
i.e. two question marks around the `await.

It might be nicer to always return a future, and in case of failure it would simply be a `future::ready(the_error)`. I.e. immediately resolve to the error when polling.

**Comment by skade** [comment]
I agree. I'll see what we can do there.

**Comment by sdroege** [comment]
If you agree with the idea I can prepare a PR :)

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
