### ISSUE TITLE
Hi, When will clone be supported?

### ISSUE THREAD

**Issue by JackDiWu** [async-rs/async-tls#32]
let tlsStream = connector.connect("www.google.com", tcpStream).await?

tlsStream.clone()??

**Comment by burdges** [comment]
[`rustls::ClientSession`](https://docs.rs/rustls/0.18.0/rustls/struct.ClientSession.html) cannot be cloned, likely because doing so makes it insecure.  You might use 0-RTT tricks to open a second stream cheaply, not sure.

**Comment by skade** [comment]
Dup of #18. Please use the discord chat or similar for inquiries.
