### ISSUE TITLE
Inappropriate patch release of `0.10.2`.

### ISSUE THREAD

**Issue by romanb** [async-rs/async-tls#42]
`0.10.2` seems to have been an inappropriate patch release, as it bumps `rustls` from `0.18` to `0.19` and `rustls` types are part of the public API of `async-tls`. This can cause downstream builds to fail (https://github.com/libp2p/rust-libp2p/issues/1873). See https://github.com/async-rs/async-tls/issues/26#issuecomment-655978761 for an analogous prior occurrence. Maybe `0.10.2` should be yanked and republished as `0.11`, as in the earlier occurrence.

**Comment by romanb** [comment]
Since quite a few downstream projects seem to have already necessarily updated to both `async-tls-0.10.2` and `rustls-0.19`, I guess this ship has sailed and yanking now would just cause more problems.

**Comment by mbrubeck** [comment]
As one of the affected downstream maintainers, I would be happy to update again if 0.10.2 is yanked.

**Comment by skade** [comment]
I, sorry for the late reply. I yanked 0.10.2 and re-released it at 0.11.0.

(FWIW, one of the reasons why I want to avoid exposing rusttls types, or rather even reduce their usage, as much as possible is this)
