### ISSUE TITLE
Upgrade to rustls 0.20.2

### ISSUE THREAD

**Issue by mfelsche** [async-rs/async-tls#45]
Are there any plans on upgrading to rustls 0.20.2?
There seem to be some breaking changes, anything that is known to be a problem?

I could lend a hand, but would need to know how to verify that everything works as expected, should a simple `cargo test --all` encompass all the necessary checks?

**Comment by silverjam** [comment]
@mfelsche attempted a port here: https://github.com/async-rs/async-tls/pull/47 -- not everything compiles and the tests don't pass... but a start I suppose

**Comment by mfelsche** [comment]
Thank you so much @silverjam gonna have a look!

**Comment by Congyuwang** [comment]
https://github.com/quininer/futures-rustls This repo is a new folk from tokio/tls, which has integrated several bug fixes/updates since the rustls v0.20 update.

**Comment by dignifiedquire** [comment]
Fixed in `0.12.0`
