### ISSUE TITLE
Cut a release to include the upgrade of rustls?

### ISSUE THREAD

**Issue by Xuanwo** [async-rs/async-tls#55]
Hi, it's been 10 months since the last async-tls release. Could we get a new one that includes the upgrade of rustls from `0.20` to `0.21`? This is currently blocking downstream crates.

cc last committer @dignifiedquire for a look, thanks.

**Comment by vorporeal** [comment]
Pinging this only because it's been 3 months since the issue was opened and there hasn't been any response or engagement from maintainers.

The latest code in the `master` branch already references rustls 0.21, it just needs a version bump and push to crates.io.

**Comment by dignifiedquire** [comment]
just published `0.13.0` with support for rustls `0.21`.

**Comment by Xuanwo** [comment]
> just published `0.13.0` with support for rustls `0.21`.

Thanks!
